export const accountDb = 'account'
export const tasksDb = 'tasks'
export const olympiadDb = 'olympiads'
export const userTasksDb = 'visited'
export const chatDb = 'chat'
export const commentsDb = 'comments'
export const AllCommentsDb = 'AllComments'
